panels/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('panels.views',
    url(r'^$', 'index', name='index'),
    url(r'^page(?P<xml_string>["-xml"]*)/(?P<page_id>\d)/(?P<slug>[\w\d\-]+)/$', 'page'),
    url(r'^archive(?P<xml_string>["-xml"]*)/(?P<selected_tag>[\w\d\s]+)/$', 'archive'),
    url(r'^archive(?P<xml_string>["-xml"]*)/$', 'archive'),
    url(r'^rss/(?P<tag>[\w\d\s]+)/$', 'rss'),
    url(r'^rss/$', 'rss'),
    url(r'^(?P<page_id>[\w\d\-]+)/$', 'static_page'),
)

panelstest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^', include('panels.urls')),
)

panels/models.py
from django.db import models
from datetime import datetime

class TagType(models.Model):
    name = models.CharField('type name', max_length = 15)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.__unicode__()

class Tag(models.Model):
    name = models.CharField('tag name', max_length = 30)
    tag_type = models.ForeignKey(TagType)

    def __unicode__(self):
        return self.name
        
    def __str__(self):
        return self.__unicode__()

class Page(models.Model):
    slug = models.SlugField(max_length=40)
    title = models.CharField('title', max_length=30, blank = True)
    pub_date = models.DateTimeField('publication date', help_text = 'The date on which this page will become visible.', default = datetime.now)
    list_date = models.DateTimeField('list date', help_text = 'The date that will be shown for this page in the archives. The publication date will be used if this field is left blank', blank = True)
    create_date = models.DateTimeField('date created', auto_now_add = True)
    modify_date = models.DateTimeField('date modified', auto_now = True)
    tags = models.ManyToManyField(Tag, blank = True, default = None)
    image = models.FileField('comic image file', upload_to = 'panels/page_images') #TODO: Make this an ImageField when support for that field is available in Python 3
    
    def get_absolute_url(self, is_xml = False):
        if (is_xml):
            return "/page-xml/%d/%s/" % (self.id, self.slug,)
        else:
            return "/page/%d/%s/" % (self.id, self.slug,)
            
    def get_xml_url(self):
        return self.get_absolute_url(True)
            
    def save(self, *args, **kwargs):
        # Populate the list date field
        if (self.list_date is None):
            self.list_date = self.pub_date
            
        # Populate the title
        if (not self.title):
            self.title = 'Comic for ' + self.list_date.strftime("%Y-%m-%d")
        
        super(Page, self).save(*args, **kwargs)
    def __unicode__(self):
        return self.title
        
    def __str__(self):
        return self.__unicode__()
	
class Note(models.Model):
    page = models.ForeignKey(Page)
    title = models.CharField('title', max_length = 30, blank = True, null = True)
    text = models.TextField('page notes')
    
class StaticPage(models.Model):
    slug = models.SlugField(max_length = 40)
    title = models.CharField('title', max_length=30, blank = False)
    content = models.TextField('content')
    
    def get_absolute_url(self):
        return "/%s-%d/" % self.slug, self.id
        
    def __unicode__(self):
        return self.title
        
    def __str__(self):
        return self.__unicode__()

panels/views.py
from datetime import datetime
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import RequestContext
from panels.models import Page, Note, Tag, TagType, StaticPage
import panels.config as config
import json, math, sys

def index(request):
    return page(request, is_index = True)
    
def page(request, page_id = None, slug = None, xml_string = None, is_index = False):
    if (xml_string == '-xml'):
        template = 'panels/page.xml'
        content_type = 'text/xml'
    else:
        template = 'panels/page.html'
        content_type = 'text/html'
    
    try:
        # Retrieve the first and last pages in the archives
        filtered_pages = Page.objects.filter(pub_date__lt = datetime.now)
    
        first_page = filtered_pages.order_by('list_date')[:1].get()
        latest_page = filtered_pages.order_by('-list_date')[:1].get()
        
        # Retrive the current page
        if (is_index):
            page = latest_page
        else:
            page = filtered_pages.get(id = page_id)

    except:
        raise Http404

    # Retrieve next page, if there is one
    try:
        next = page.get_next_by_list_date(pub_date__lt = datetime.now)
    except Page.DoesNotExist:
        next = False
    
    # Retrieve previous page, if there is one
    try:
        prev = page.get_previous_by_list_date(pub_date__lt = datetime.now)
    except Page.DoesNotExist:
        prev = False
    
    # Retrieve list of static pages
    static_pages = StaticPage.objects.all()
    
    return render_to_response(
        template,
        {
            'comic_title' : config.comic_title,
            'comic_description' : config.comic_description,
            'page' : page,
            'first' : first_page,
            'prev' : prev,
            'next' : next,
            'latest' : latest_page,
            'is_index' : is_index,
            'media_url' : settings.MEDIA_URL,
            'root_url' : request.build_absolute_uri('/'),
            'display_social_buttons' : config.display_social_buttons,
            'static_pages' : static_pages,
        },
        mimetype = content_type,
    )
    
def archive(request, xml_string = None, selected_tag = False):
    if (xml_string == '-xml'):
        template = 'panels/archive.xml'
        content_type = 'text/xml'
        # Don't bother getting the static pages if we're just generating XML
        static_pages = None
    else:
        template = 'panels/archive.html'
        content_type = 'text/html'
        # Retrieve list of static pages
        static_pages = StaticPage.objects.all()

    got_page_list = False
    filtered_for_tag = False

    if (selected_tag):
        pages = Page.objects.filter(tags__name__exact = selected_tag).all()
        if (pages):
            got_page_list = True
            filtered_for_tag = True
    
    if (not got_page_list):
        pages = Page.objects.all()
        
    all_tags = get_tags()
    tag_types = TagType.objects.all()
        
    return render_to_response(
        template,
        {
            'filtered_for_tag' : filtered_for_tag,
            'selected_tag' : selected_tag,
            'pages' : pages,
            'all_tags' : all_tags,
            'tag_types' : tag_types,
            'static_pages' : static_pages,
            'media_url' : settings.MEDIA_URL,
            'comic_title' : config.comic_title,
            'comic_description' : config.comic_description,
            'display_tagtype_selector' : config.display_tagtype_selector,
            'root_url' : request.build_absolute_uri('/'),
        },
        mimetype = content_type
    )
    
def rss(request, tag = None):
    got_page_list = False
    feed_description = config.comic_description

    if (tag):
        pages = Page.objects.filter(tags__name__exact = tag).all()
        if (pages):
            got_page_list = True
            feed_description += ' - Tag: ' + tag
            
    if (not got_page_list):
        pages = Page.objects.all()
        
    return render_to_response(
        'panels/rss.xml',
        {
            'comic_title' : config.comic_title,
            'feed_description' : feed_description,
            'link' : request.build_absolute_uri('/'),
            'pages' : pages,
        },
        mimetype = 'text/xml'
    )
    
def static_page(request, page_id):
    page = get_object_or_404(StaticPage, slug__exact = page_id)
    
    # Retrieve list of static pages
    static_pages = StaticPage.objects.all()
    
    return render_to_response(
        'panels/static.html',
        {
            'page' : page,
            'static_pages' : static_pages,
            'comic_title' : config.comic_title,
            'comic_description' : config.comic_description,
            'media_url' : settings.MEDIA_URL,
            'root_url' : request.build_absolute_uri('/'),
        },
        mimetype = 'text/html'
    )
            
    
def get_tags():
    total_pages = Page.objects.count()
    tags = Tag.objects.all()
    tag_list = []
    most_frequent_tag = 0
    
    for tag in tags:
        tag_appearances = Page.objects.filter(tags__id__exact = tag.id).count()
        
        if (tag_appearances > 0):
            tag_list.append({'object' : tag, 'appearances' : tag_appearances,})
            if (tag_appearances > most_frequent_tag):
                most_frequent_tag = tag_appearances
    
    if sys.version_info < (3,):
        tag_range = xrange(len(tag_list))
    else:
        tag_range = range(len(tag_list))
    
    for i in tag_range:
        tag_list[i]['magnitude'] = int(math.ceil(math.log(tag_list[i]['appearances']) / math.log(most_frequent_tag) * 10))
    
    return tag_list

panels/templates/panels/archive.html
{% extends "panels/panels.html" %}
{% load staticfiles %}
{% block js_includes %}
{{ block.super }}
    <script src = "{% static "js/archive.js" %}" type = "text/javascript"></script>
{% endblock %}
{% block css_includes %}
{{ block.super }}
    <link rel = "stylesheet" href = "{% static "css/archive.css" %}" />
{% endblock %}
{% block css %}
    <style>
    #tagHeader {
    {% if filtered_for_tag %}
        display: inline;
    {% else %}
        display: none;
    {% endif %}
    }
    </style>
{% endblock %}
{% block content %}
    <section id = "pageList" class = "contentBox">
        <header>
            <h1>Archives<span id = "tagHeader"> for <span id = "currentTag">{{ selected_tag }}</span></span></h1>
        </header>
        <article>
            <ul>
            {% for page in pages %}
                <li><a href = "{{ page.get_absolute_url|escape }}" title = "{{ page.list_date.date }}">{{ page.title|escape }}</a></li>
            {% endfor %}
            </ul>
        </article>
    </section>
    
    <section id = "tagCloud" class = "contentBox">
        <header>
            <h1>Tags</h1>
        </header>
        {% if display_tagtype_selector %}
        <p id = "tagTypeSelector">
            <label for = "tagTypeList">Tag type:</label>
            <select id = "tagTypeList">
                <option value = "">all</option>
            {% for tag_type in tag_types %}
                <option>{{ tag_type.name|escape }}</option>
            {% endfor %}
            </select>
        </p>
        {% endif %}
        
        <ul id = "tagList">
        {% for tag in all_tags %}
            <li class = "tag {{ tag.object.tag_type.name|escape }} magnitude-{{ tag.magnitude}}{% if tag.object.name == selected_tag %} selected{% endif %}"><a href = "/archive/{{ tag.object.name|escape }}/">{{ tag.object.name|escape }}</a></li>
        {% endfor %}
        </ul>
    </section>
{% endblock %}

panels/templates/panels/page.html
{% extends "panels/panels.html" %}
{% load staticfiles %}
{% block js_includes %}
{{ block.super }}
    <script src = "{% static "js/panels.js" %}" type = "text/javascript"></script>
{% endblock %}
{% block css_includes %}
{{ block.super }}
    <link rel = "stylesheet" href = "{% static "css/page.css" %}" />
{% endblock %}
{% block javascript %}
    <script type = "text/javascript">
    var firstUrl = '{{ first.get_absolute_url|escapejs }}';
    var firstXmlUrl = '{{ first.get_xml_url|escapejs }}';
{% if prev %}
    var prevUrl = '{{ prev.get_absolute_url|escapejs }}';
    var prevXmlUrl = '{{ prev.get_xml_url|escapejs }}';
    var prevImageUrl = '{{ prev.image.url|escapejs }}';
{% else %}
    var prevUrl = null;
    var prevXmlUrl = null;
    var prevImageUrl = null;
{% endif %}
{% if next %}
    var nextUrl = '{{ next.get_absolute_url|escapejs }}';
    var nextXmlUrl = '{{ next.get_xml_url|escapejs }}';
    var nextImageUrl = '{{ next.image.url|escapejs }}';
{% else %}
    var nextUrl = null;
    var nextXmlUrl = null;
    var nextImageUrl = null;
{% endif %}
    var latestUrl = '{{ latest.get_absolute_url|escapejs }}';
    var latestXmlUrl = '{{ latest.get_xml_url|escapejs }}';
    
    var currentImageUrl = '{{ page.image.url|escapejs }}';
    
    var rootUrl = '{{ root_url|escapejs }}';
    
    {% if display_social_buttons %}
    var displaySocialButtons = true;
    {% else %}
    var displaySocialButtons = false;
    {% endif %}
    </script>
{% endblock %}
{% block css %}
    <style>
    {% if prev %}
    #prevPage .link {
        display: block;
    }
    #prevPage .noLink {
        display: none;
    }
    #firstPage .link {
        display: block;
    }
    #firstPage .noLink {
        display: none;
    }
    {% else %}
    #prevPage .link {
        display: none;
    }
    #prevPage .noLink {
        display: block;
    }
    #firstPage .link {
        display: none;
    }
    #firstPage .noLink {
        display: block;
    }
    {% endif %}
    
    {% if next %}
    #nextPage .link {
        display: block;
    }
    #nextPage .noLink {
        display: none;
    }
    #latestPage .link {
        display: block;
    }
    #latestPage .noLink {
        display: none;
    }
    {% else %}
    #nextPage .link {
        display: none;
    }
    #nextPage .noLink {
        display: block;
    }
    #latestPage .link {
        display: none;
    }
    #latestPage .noLink {
        display: block;
    }
    {% endif %}
    
    #comicLoading {
        display: none;
    }
    </style>
{% endblock %}
{% block content %}
    <section id = "comicData" class = "contentBox">
        <header>
            <h1>{{ page.title|escape }}</h1>
        </header>
        <article>
            <div id = "comicImage">
                <div id = "firstPage">
                    <a class = "link" href = "{{ first.get_absolute_url|escape }}" rel = "start"><span class = "invisibleText">First</span></a>
                    <span class = "noLink"><span class = "invisibleText">First</span></span>
                </div>
                <div id = "prevPage">
                    <a class = "link"  href = "{% if prev %}{{ prev.get_absolute_url|escape }}{% endif %}" rel = "prev"><span class = "invisibleText">Previous</span></a>
                    <span class = "noLink"><span class = "invisibleText">Previous</span></span>
                </div>
                <img src = "{{ page.image.url }}" alt = "" />
                <div id = "nextPage">
                    <a class = "link"  href = "{% if next %}{{ next.get_absolute_url|escape }}{% endif %}" rel = "next prefetch"><span class = "invisibleText">Next</span></a>
                    <span class = "noLink"><span class = "invisibleText">Next</span></span>
                </div>
                <div id = "latestPage">
                    <a class = "link"  href = "{{ latest.get_absolute_url|escape }}"><span class = "invisibleText">Latest</span></a>
                    <span class = 'noLink'><span class = "invisibleText">Latest</span></span>
                </div>
                    <div id = "comicLoading">
                        Loading...
                    </div>
            </div>
            <a id = "permalink" href = "{{ page.get_absolute_url|escape }}">
                <time datetime = "{{ page.list_date.date|date:"Y-m-d"}}" pubdate = "pubdate">{{ page.list_date.date|date:"F j, Y" }}</time>
            </a>
            
            <ul id = "comicTags">
                <lh>Tags:</lh>
                {% for tag in page.tags.all %}
                <li class = "tag {{ tag.tag_type|escape }}"><a href = "/archive/{{ tag.name|escape }}/">{{ tag.name|escape }}</a></li>
                {% endfor %}
            </ul>
        </article>
        {% if display_social_buttons %}
        <section id = "social">
            <!-- Lockerz Share BEGIN -->
            <a id = "lockerzLink" href="http://www.addtoany.com/share_save?linkurl={{ root_url|iriencode }}page/{{ page.slug|iriencode }}&amp;linkname={{ page.title|iriencode }}"><img src="http://static.addtoany.com/buttons/share_save_171_16.png" width="171" height="16" border="0" alt="Share"/></a>
            <!-- Lockerz Share END -->
        </section>
        {% endif %}
    </section>
    <section id = "comicNotes">
    {% for note in page.note_set.all %}
        <section class = "contentBox">
            <header>
                <h1>{% if note.title %}{{ note.title }}{% else %}Notes{% endif %}</h1>
            </header>
            <article>
                {{ note.text|safe }}
            </article>
        </section>
    {% endfor %}
    </section>
{% endblock %}

panels/templates/panels/panels.html
<!DOCTYPE html>
<html lang = "en">
<head>
    {% load staticfiles %}
    <meta charset = "utf-8" />
    <title>{% block title %}{{ comic_title }}{% endblock %}</title>
    <!--[if lt IE 9]>
        <script src = "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% block js_includes %}
    <script src = "{% static "includes/jquery-1.11.0.min.js" %}" type = "text/javascript"></script>
    {% endblock %}
    {% block css_includes %}
    <link rel = "stylesheet" href = "{% static "css/panels.css" %}" />
    <link rel = "stylesheet" href = "{% static "css/magnitude.css" %} " />
    {% endblock %}
    <link rel="alternate" type = "application/rss+xml" title = "RSS" href = "{{ root_url }}/rss/" />
    {% block javascript %}{% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
    {% block main_header %}
    <header id = "mainHeader">
        <h1>{{ comic_title }}</h1>
        <h2>{{ comic_description }}</h2>
    </header>
    {% endblock %}
    {% block site_nav %}
    <nav id = "siteNav">
        <ul>
            <li><a href="{{ root_url }}archive">Archive</a></li>
            <li><a href = "{{ root_url }}">Main</a></li>
            {% for static_page in static_pages %}
            <li><a href="{{ root_url }}{{ static_page.slug }}/">{{ static_page.title }}</a></li>
            {% endfor %}
            <li><a href="{{ root_url }}rss">RSS</a></li>
        </ul>
    </nav>
    {% endblock %}
    {%block content %}{% endblock %}
</body>
</html>

panels/templates/panels/static.html
{% extends "panels/panels.html" %}
{% load staticfiles %}
{% block content %}
    <section class = "contentBox">
        <header>
            <h1>{{ page.title }}</hi>
        </header>
        <article>
            {{ page.content|safe }}
        </article>
    </section>
{% endblock %}